require 'brainclusterfuck/opcodes/modify_value'
require 'brainclusterfuck/opcodes/modify_pointer'
require 'brainclusterfuck/opcodes/print'
require 'brainclusterfuck/opcodes/loop_start'
require 'brainclusterfuck/opcodes/loop_end'
